name:                izuna-example
version:             0.1.0.0
github:              "githubuser/izuna-example"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
  - -fwrite-ide-info
  - -hiedir=.hie

description:         Please see the README on GitHub at <https://github.com/githubuser/izuna-example#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  izuna-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - izuna-example

tests:
  izuna-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - izuna-example
