on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: build project info for izuna
      id: hello
      uses: matsumonkie/izuna-action@v0.2
      with:
        packageName: 'izuna-example'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"