on:
  # Trigger the workflow on push or pull request, but only for the main/master branch
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack: ["2.3.1"]
        ghc: ["8.10.1"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main' || github.event.ref == 'refs/head/master'

    - uses: haskell/actions/setup@v1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - uses: actions/cache@v2
      name: Cache Stack build
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        # when merging a PR on your main branch, if you have setup a cache, you will probably don't need to build your project
        # so let's make sure we generate the .hie files if our cache doesn't have them!
        stack build --force-dirty

    - name: build project info for izuna
      uses: matsumonkie/izuna-action@v0.53
      with:
        package: 'izuna-example'
        ghcVersion: '8.10.1'
        hieDirectory: '.hie/'
