on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: build project info for izuna
      id: hello
      uses: matsumonkie/izuna-action@v0.9
      with:
        packageName: 'izuna-example'
        ghcVersion: '8.10.1'
